source 'https://rubygems.org'
ruby '2.2.3'

gem 'sinatra'
gem 'dm-postgres-adapter'
gem 'dm-ar-finders'
gem 'sinatra-partial'
gem 'rest-client'
gem 'pg'

group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'factory_girl'
  gem 'database_cleaner'
  gem 'nyan-cat-formatter'
end
