# Generated by rspec-sinatra. (2016-07-27 17:32:57 +0100)

ENV['RACK_ENV'] = 'test'

require 'capybara'
require 'capybara/rspec'
require 'rspec'
require 'factory_girl'
# require 'nobrainer_helper'

require File.join(File.dirname(__FILE__), '..', 'app/app.rb')

Capybara.app = Varys

RSpec.configure do |config|
  config.include Capybara::DSL
  config.include FactoryGirl::Syntax::Methods

  FactoryGirl.definition_file_paths = %w{./factories ./test/factories ./spec/factories}
  FactoryGirl.find_definitions

  config.before :all do
    FactoryGirl.reload
    NoBrainer.drop!
    NoBrainer.sync_schema
  end

  config.before :each do
    NoBrainer.purge!
  end

  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end
end
