# Generated by rspec-sinatra. (2016-07-27 17:32:57 +0100)

ENV['RACK_ENV'] = 'test'

require 'capybara'
require 'capybara/rspec'
require 'rspec'
require 'factory_girl'

require File.join(File.dirname(__FILE__), '..', 'app/app.rb')

Capybara.app = Varys

RSpec.configure do |config|
  config.include Capybara::DSL
  config.include FactoryGirl::Syntax::Methods
  config.include Rack::Test::Methods

  FactoryGirl.definition_file_paths = %w{./factories ./test/factories ./spec/factories}
  FactoryGirl.find_definitions

  def app
    Sinatra::Application
  end

  config.before(:all) do
    FactoryGirl.reload
  end

  config.after(:each) do
    begin
      connection = PG.connect :dbname => 'varys_' + ENV['RACK_ENV']
      connection.exec "TRUNCATE webpages;"
    rescue PG::Error => e
      puts e.message
    ensure
      connection.close if connection
    end
  end

  config.expect_with(:rspec) do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with(:rspec) do |mocks|
    mocks.verify_partial_doubles = true
  end
end
