# Generated by rspec-sinatra. (2016-07-27 17:32:57 +0100)

ENV['RACK_ENV'] = 'test'

require 'capybara'
require 'capybara/rspec'
require 'rspec'

require File.join(File.dirname(__FILE__), '..', 'app/app.rb')

Capybara.app = Varys

RSpec.configure do |config|
  config.alias_example_group_to :feature
  config.include Capybara::DSL
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end
end
